# Site settings
name: Speak
email: junglespeak@gmail.com
description: "A Volcano of Vocabularising.\n  俳句 Haiku short poetry.\n  Graphic, Efficient, Rapid Communication Bricks.\n   Use me to get a clue and to get the message through!\n  And pass me on... "

keywords: [mean catchphrase, awesomely geek, really serious, proper english, singlish lah, excellent spread knowledge, make sense]

copyright: Single Authors
license: Creative Commons Attribution 4.0 International license.
license_link: http://creativecommons.org/licenses/by/4.0/
# production
baseurl: ""
url: "http://speak.junglestar.org"
twitter: jungle_speak
timezone: Europe/London
version: 0.14.0
version_code_name: "penguin flight"
google_analytics: UA-54058429-1

# Build settings
permalink: /:title/
excerpt_separator: <!--more-->

# Filtering Content
show_drafts: null
limit_posts: 0
future: false
unpublished: false
exclude: [gulpfile.js, node_modules, package.json, icon, Gemfile, Gemfile.lock, vendor]

#setup
sass:
  sass_dir: _sass
  style: :compressed
  #style: :expanded

gems:
  - jekyll-feed
  - github-pages
  - html-proofer
  - jekyll-sitemap
  - jekyll-seo-tag

#turn off if something is not working:
compress_html:
  clippings: [div, p, ul, td, h1, h2, h3, h4, h5, h6, ]
  comments: []
  endings: []
  profile: false
  ignore:
    envs: []


### Quick how2

## run jekyll using:
# $ bundle exec jekyll serve --baseurl

## run gulp in a new ternimal window after jekyll
# $ gulp

## ref: https://help.github.com/articles/using-jekyll-with-pages/#running-jekyll
