# Site settings
title: Speak
email: speak@junglestar.org
description: " | A Volcano of vocabularising | 俳句 Haiku short poetry | Graphic, Efficient, Rapid Communication Bricks | Who? its a second click quest and Pleasure! | Use me to get a clue and to get the message through! | btw, nice colors nah... "
baseurl: ""
url: "http://speak.junglestar.org"
twitter_username: rokmatwit
timezone: Europe/London
version: 0.6.0
analytics: UA-54058429-1

# Build settings
# markdown: kramdown
permalink: pretty

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

#setup
sass:
  sass_dir: _sass
  #style: :compressed
  style: :expanded
