# Site settings
title: Speak
email: speak@junglestar.org
description: " | A Volcano of vocabularising | 俳句 Haiku short poetry | Graphic, Efficient, Rapid Communication Bricks | Who? its a second click quest and Pleasure! | Use me to get a clue and to get the message through! | btw, nice colors nah... "
baseurl: "/speak"
url: "https://toybreaker.github.io"
twitter_username: rokmatwit
timezone: Europe/London
version: 0.6.0
google_analytics: UA-54058429-1

# Build settings
# markdown: kramdown
permalink: /:categories/:title/

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

#setup
sass:
  sass_dir: _sass
  style: :compressed
  #style: :expanded


## how2 (tests show this is not really needed... ?!)
## https://help.github.com/articles/using-jekyll-with-pages/#running-jekyll
## run jekyll using:
# bundle exec jekyll serve
# or maybe:
# bundle exec jekyll serve --baseurl ''

## cos this is on gh-pages when running it locally use:
## jekyll serve --baseurl ''
