# Site settings
name:                     Speak
email:                    junglespeak@gmail.com
description:              "A Volcano of Vocabularising.\n  俳句 Haiku short poetry.\n  Graphic, Efficient, Rapid Communication Bricks.\n   Use me to get a clue and to get the message through!\n  And pass me on... "

keywords:                 [mean catchphrase, awesomely geek, really serious, proper english, singlish lah, excellent spread knowledge, make sense]

copyright:                Single Authors
license:                  Creative Commons Attribution 4.0 International license.
license_link:             https://creativecommons.org/licenses/by/4.0/
# production
baseurl:                  ""
url:                      "https://speak.junglestar.org"
twitter:                  jungle_speak
timezone:                 Europe/London
version:                  1.2.6
version_code_name:        "COCONUT WIRELESS"
google_analytics:         G-417J9W8JJ1
google_site_verification: Rt71Q1qGvbUviohh6n8KmtRoGUd-XeuuuKLBjCMvHO8
repository:               junglesta/speak

# Build settings
permalink:                /:title/
excerpt_separator:        <!--more-->

# Filtering Content
show_drafts:              null
limit_posts:              0
future:                   false
unpublished:              false
exclude:                  [gulpfile.js, node_modules, package.json, icon, Gemfile, Gemfile.lock, vendor]

#setup
sass:
  sass_dir:               _sass
  style:                  :compressed
  #style:                 :expanded

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

#seo-tag
twitter:
 username:                rokmatwit
 card:                    summary

defaults:
  - scope:
      path:               ""
    values:
      image:              /assets/twittercard/twittercard.png

#turn off if something is not working:
compress_html:
  clippings:              [div, p, ul, td, h1, h2, h3, h4, h5, h6, ]
  comments:               []
  endings:                []
  profile:                false
  ignore:
    envs:                 []

#need for docker, read here:
#https://dev.to/michael/compile-a-jekyll-project-without-installing-jekyll-or-ruby-by-using-docker-4184
exclude:
  - "package.json"
  - "README.md"
  - "publish.sh"
  - "vendor"
